org.gradle.jvmargs=-Xmx1400m -Dfile.encoding=UTF-8 -XX:+UseSerialGC -XX:MaxMetaspaceSize=512m
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.daemon.idletimeout=600000
kotlin.daemon.jvmargs=-Xmx900m
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
